blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'blog'

urlpatterns = [
    path('', login_required(views.Home.as_view()), name='home'),
    path('tag/create/', login_required(views.TagCreateView.as_view()), name='tag_create'),
    path('kiji/create/', login_required(views.KijiCreateView.as_view()), name='kiji_create'),
    path('kiji/detail/<int:pk>', login_required(views.KijiDetailView.as_view()), name='kiji_detail'),
    path('kiji_update/<int:pk>/', login_required(views.KijiUpdate.as_view()), name='kiji_update'),
    path('kiji_delete/<int:pk>/',login_required(views.KijiDelete.as_view()), name='kiji_delete'),
    path('comment/create/<int:pk>',login_required(views.CommentCreateView.as_view()), name='comment_create'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('chat/', include('chat.urls')),
    path('homework/', include('homework.urls')),
    path('timetable/', include('timetable.urls')),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timetable/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'timetable'

urlpatterns =[
    # path('test/', views.Test.as_view(), name='test'),
    path('timetable_create/', views.TimetableCreateView.as_view(), name='timetable_create'),
    # path('timetable_list/', views.TimetableListView.as_view(), name='timetable_list'),
    path('timetable_list/', views.TimetableView.as_view(), name='timetable_list'),
    path('timetable_detail/<int:pk>/', views.TimetableDetailView.as_view(), name='timetable_detail'),
    path('timetable_delete/<int:pk>/', views.TimetableDeleteView.as_view(), name='timetable_delete'),
    path('timetable_update/<int:pk>/', views.TimetableUpdateView.as_view(), name='timetable_update'),
    path('subject_create/', views.SubjectCreateView.as_view(), name='subject_create'),
    path('subject_list/', views.SubjectListView.as_view(), name='subject_list'),
    # path('lunchmenu_create/', views.LunchmenuCreateView.as_view(), name='lunchmenu_create'),
    # path('lunchmenu_create/<int:pk>', views.LunchmenuCreateView.as_view(), name='lunchmenu_create'),
    # path('lunchmenu_list/', views.LunchmenuListView.as_view(), name='lunchmenu_list'),
    path('lunchmenu_detail/<int:pk>/', views.LunchmenuDetailview.as_view(), name='lunchmenu_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timetable/models.py
from django.db import models
from django.utils import timezone

class Subject(models.Model):
    name = models.CharField('教科名', max_length=255)

    def __str__(self):
        return self.name


class Timetable(models.Model):
    day = models.DateField('日付　　', default=timezone.now)   #timezone.now：現在時間の取得
    FirstPeriod = models.ForeignKey(Subject, on_delete=models.PROTECT, verbose_name='１時間目', related_name='FirstPeriod',default=1)
    firsttext = models.CharField('授業内容', max_length=30, default="")
    SecondPeriod = models.ForeignKey(Subject, on_delete=models.PROTECT, verbose_name='２時間目', related_name='SecondPeriod', default=2)
    secondtext = models.CharField('授業内容', max_length=30, default="")
    ThirdPeriod = models.ForeignKey(Subject, on_delete=models.PROTECT, verbose_name='３時間目', related_name='ThirdPeriod', default=3)
    thirdtext = models.CharField('授業内容', max_length=30, default="")
    FourthPeriod = models.ForeignKey(Subject, on_delete=models.PROTECT, verbose_name='４時間目', related_name='FourthPeriod', default=4)
    fourthtext = models.CharField('授業内容', max_length=30, default="")
    FifthPeriod = models.ForeignKey(Subject, on_delete=models.PROTECT, verbose_name='５時間目', related_name='FifthPeriod', default=5)
    fifthtext = models.CharField('授業内容', max_length=30, default="")
    SixthPeriod = models.ForeignKey(Subject, on_delete=models.PROTECT, verbose_name='６時間目', related_name='SixthPeriod', default=6)
    sixthtext = models.CharField('授業内容', max_length=30, default="")
    text = models.TextField('必要な物')   #TextField : 複数行のテキスト入力行になる
    image = models.ImageField('献立画像', null=True, blank=True, upload_to='lunchmenu_images/')
    menu = models.TextField('献立　　')
    explain = models.TextField('説明　　')  # TextField : 複数行のテキスト入力行になる


    def __str__(self):
        return str(self.day)

    class Meta:
        ordering = ('day',) #dayで昇順ソート

# class Lunchmenu(models.Model):
#     day = models.ForeignKey(
#         Timetable, on_delete=models.SET_NULL,
#         blank=True, null=True,
#         verbose_name='日付'
#     )
#     image = models.ImageField('献立画像', null=True, blank=True, upload_to='goods_images/')
#     menu = models.TextField('献立', default='1')
#     explain = models.TextField('説明', default='1')  # TextField : 複数行のテキスト入力行になる

timetable/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

from .models import Timetable, Subject

class DateInput(forms.DateInput):
    input_type='date'

class TimetableCreateForm(forms.ModelForm):

    class Meta:
        model = Timetable
        fields = '__all__'
        # fields = ('day','subject', 'text')
        # fields = ('day', 'subject', 'subject','subject','subject','subject','subject', 'text')
        # fields = ('day', 'FirstPeriod', 'SecondPeriod', 'ThirdPeriod', 'FourthPeriod', 'FifthPeriod',
        #           'SixthPeriod', 'text')
        widgets = {
            'day': DateInput()
        }

class SubjectCreateForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'

class TimetableUpdateForm(forms.ModelForm):
    class Meta:
        model = Timetable
        # fields = ('day', 'subject', 'text')
        fields = '__all__'

# class LunchmenuCreateForm(forms.ModelForm):
#     class Meta:
#         model = Lunchmenu
#         fields = ('image', 'menu', 'explain')

class TimetableSearchForm(forms.Form):
    day = forms.DateField(label='日付', required=False)

class YearMonthForm(forms.Form):
    year = forms.IntegerField()
    month = forms.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(12)])

timetable/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView, View
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import Timetable, Subject
from .forms import TimetableCreateForm, SubjectCreateForm, TimetableUpdateForm, TimetableSearchForm, YearMonthForm

# class Test(TemplateView):
#     template_name = 'timetable/test.html'

class TimetableCreateView(CreateView):
    model = Timetable
    template_name = 'timetable/timetable_create.html'
    success_url = reverse_lazy('timetable:timetable_list')
    form_class = TimetableCreateForm

    def users(request, user_age):
        user = get_object_or_404(User, pk=user_age)
        context2 = {
            'user': user,
        }
        return context2


class TimetableView(View):
    model = Timetable
    template_name = 'timetable/timetable_list.html'
    form_class = TimetableSearchForm
    paginate_by = 30

    def users(request, user_age):
        user = get_object_or_404(User, pk=user_age)
        context2 = {
            'user': user,
        }
        return context2

    def get(self, request, *args, **kwargs):

        context = {}

        form = YearMonthForm(request.GET)
        if form.is_valid():
            cleaned = form.clean()

            context["timetable"] = Timetable.objects.filter(day__year=cleaned["year"], day__month=cleaned["month"]).order_by(
                "-day")
        else:
            context["timetable"] = Timetable.objects.order_by("-day")

        # 月別アーカイブの表示
        # 最新と最古のデータを手に入れる。
        newest = Timetable.objects.order_by("-day").first()
        oldest = Timetable.objects.order_by("day").first()

        year_month_list = []

        if newest and oldest:

            newest_day = newest.day
            now_year = oldest.day.year
            now_month = oldest.day.month

            # 最古から1ヶ月ずつずらして最新になったら終わり
            while True:
                year_month = {}
                year_month["link"] = "?year=" + str(now_year) + "&month=" + str(now_month)
                year_month["label"] = str(now_year) + "年" + str(now_month) + "月"

                copied = year_month.copy()

                year_month_list.append(copied)

                if now_month >= newest_day.month and now_year >= newest_day.year:
                    break
                else:
                    if now_month == 12:
                        now_year += 1
                        now_month = 1
                    else:
                        now_month += 1

        context["year_month_list"] = year_month_list

        return render(request, "timetable/timetable_list.html", context)

index = TimetableView.as_view()

class TimetableDeleteView(DeleteView):
    model = Timetable
    template_name = 'timetable/timetable_delete.html'
    success_url = reverse_lazy('timetable:timetable_list')

    def users(request, user_age):
        user = get_object_or_404(User, pk=user_age)
        context2 = {
            'user': user,
        }
        return context2

class TimetableDetailView(DetailView):
    model = Timetable
    template_name = 'timetable/timetable_detail.html'

    def users(request, user_age):
        user = get_object_or_404(User, pk=user_age)
        context2 = {
            'user': user,
        }
        return context2

class TimetableUpdateView(UpdateView):
    model = Timetable
    form_class = TimetableUpdateForm
    template_name = 'timetable/timetable_update.html'
    success_url = reverse_lazy('timetable:timetable_list')

    def users(request, user_age):
        user = get_object_or_404(User, pk=user_age)
        context2 = {
            'user': user,
        }
        return context2

class SubjectCreateView(CreateView):
    model = Subject
    template_name = 'timetable/subject_create.html'
    success_url = reverse_lazy('timetable:subject_list')
    form_class = SubjectCreateForm

class SubjectListView(ListView):
    model = Subject
    template_name = 'timetable/subject_list.html'

class LunchmenuDetailview(DetailView):
    model = Timetable
    template_name = 'timetable/lunchmenu_detail.html'

    def users(request, user_age):
        user = get_object_or_404(User, pk=user_age)
        context2 = {
            'user': user,
        }
        return context2
#
# class LunchmenuCreateView(CreateView):
#     model = Lunchmenu
#     form_class = LunchmenuCreateForm
#     template_name = 'timetable/lunchmenu_create.html'
#     success_url = reverse_lazy('timetable:lunchmenu_list')
#
#     # def form_valid(self, form):
#     #     lunchmenu = form.save(commit=False)  # データベースには保存しない
#     #     lunchmenu.target = Timetable.objects.get(pk=self.kwargs['pk'])
#     #     lunchmenu.save()
#     #     return redirect('timetable:lunchmenu_create')
#
# class LunchmenuListView(ListView):
#     model = Lunchmenu
#     template_name = 'timetable/Lunchmenu_list.html'

templates/timetable/lunchmenu_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>献立作成ページ</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="save" value="作成">
</form>
</body>
</html>

templates/timetable/lunchmenu_detail.html
{% extends 'base_chat.html' %}
{% block content %}
{% if user.age < 17 %}
    <div class="nico" align="center">
         <h2>{{ object.day }}のこんだて</h2>
        {% if object.image %}
          <img src="{{ object.image.url }}">
        {% endif %}
        <table border="3" bordercolor="#00bfff" width="350" height="100" align="center">
            <tr bgcolor="#00ffff">
                <th>こんだてないよう</th>
            </tr>
            <tr bgcolor="#f5f5f5">
                <td>{{ object.menu | linebreaksbr }}</td>
            </tr>
        </table>
        <br>
        <table border="3" bordercolor="#00bfff" width="500" height="100" align="center">
            <tr bgcolor="#00ffff">
                <th>せつめい</th>
            </tr>
            <tr bgcolor="#f5f5f5">
                <td>{{ object.explain | linebreaksbr }}</td>
            </tr>
        </table>
        <div class="rightside-contents-form">
            <br>
            <a href="{% url 'timetable:timetable_detail' timetable.id %}">
                <input class="yk-button" type="submit" value="じかんわりページにもどる">
            </a>
        </div>
    </div>
{% else %}
    <div class="kuroro" align="center">
        <h2>{{ object.day }}の献立</h2>
        {% if object.image %}
          <img src="{{ object.image.url }}">
        {% endif %}
        <table border="3" bordercolor="#00bfff" width="350" height="100" align="center">
            <tr bgcolor="#00ffff">
                <th>献立内容</th>
            </tr>
            <tr bgcolor="#f5f5f5">
                <td>{{ object.menu | linebreaksbr }}</td>
            </tr>
        </table>
        <br>
        <table border="3" bordercolor="#00bfff" width="500" height="100" align="center">
            <tr bgcolor="#00ffff">
                <th>説明</th>
            </tr>
            <tr bgcolor="#f5f5f5">
                <td>{{ object.explain | linebreaksbr }}</td>
            </tr>
        </table>
        <div class="rightside-contents-form">
            <br>
            <a href="{% url 'timetable:timetable_detail' timetable.id %}">
                <input class="yk-button" type="submit" value="時間割詳細ページに戻る">
            </a>
        </div>
    </div>
{% endif %}
{% endblock %}

templates/timetable/lunchmenu_list.html
{% extends 'base_chat.html' %}
{% block content %}

{% if user.age < 17 %}
    <div class="nico">
        <h2>きゅうしょくのこんだてリスト</h2>
            <a href="{% url 'timetable:lunchmenu_create' %}">作成</a>
            {% for menu in lunchmenu_list %}
                <a href="{% url 'timetable:lunchmenu_detail' menu.id %}">{{ menu.day }}</a>
            {% endfor %}
    </div>
{% else %}
    <div class="kokoro">
        <h2>konn</h2>
            <a href="{% url 'timetable:lunchmenu_create' %}">作成</a>
            {% for menu in lunchmenu_list %}
                <a href="{% url 'timetable:lunchmenu_detail' menu.id %}">{{ menu.day }}</a>
            {% endfor %}
    </div>
{% endblock %}

templates/timetable/subject_create.html
{% extends 'base_chat.html' %}
{% block content %}
  <h1>教科作成ページ</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_div }}
    <button type="submit">送信</button>
  </form>
{% endblock %}

templates/timetable/subject_list.html
{% extends 'base_chat.html' %}
{% block content %}
    <h1>教科 一覧ページ</h1>
    <div>
        {% for subject in subject_list %}
        <p>{{ subject.name }}</p>
        {% endfor %}
    </div>
    <a href="{% url 'timetable:subject_create' %}">
        <input type="submit" value="教科を作成">
    </a>
{% endblock %}

templates/timetable/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
    <h1>this is Test page</h1>
</body>
</html>

templates/timetable/timetable_create.html
{% extends 'base_chat.html' %}
{% block content %}
<div align="origin">
  <h1>時間割 & 給食の献立作成ページ</h1>
  <form action="" method="POST" enctype="multipart/form-data" class="create">
    {% csrf_token %}
    {{ form.as_div }}
     <div class="rightside-contents-form" align="center">
         <button type="submit" class="yk-button" >送信</button>
     </div>
  </form>
</div>
{% endblock %}

templates/timetable/timetable_delete.html
{% extends 'base_chat.html' %}
{% block content %}
<div class="kokoro">
    <form method="post">{% csrf_token %}
        <p>"{{ object }}"の時間割を削除してもよろしいですか?</p>
        <input type="submit" value="削除" class="button">
    </form>
    <a href="{% url 'timetable:timetable_list' %}">
        <input type="submit" value="キャンセル" class="button">
    </a>
</div>
{% endblock %}

templates/timetable/timetable_detail.html
{% extends 'base_chat.html' %}
{% block content %}

{% if user.age < 17 %}
    <div class="nico">
        <h1 align="center">{{ timetable.day }}のじかんわり</h1>
        <table border="3" bordercolor="#00bfff" width="400" height="500" align="center">
            <tr bgcolor="#00ffff" align="center" valign="center">
                <th></th>
                <th>じゅぎょう</th>
                <th >ないよう</th>
            </tr>
            <tr bgcolor="#f5f5f5"  align="center" valign="center">
                <td colspan="3">あさのかい</td>
            </tr>
            <tr bgcolor="#f5f5f5"  align="center" valign="center">
                <td>１じかんめ</td>
                <td>{{ timetable.FirstPeriod }}</td>
                <td>{{ timetable.firsttext }}</td>
            </tr>
            <tr bgcolor="#f5f5f5"  align="center" valign="center">
                <td>２じかんめ</td>
                <td>{{ timetable.SecondPeriod }}</td>
                <td>{{ timetable.secondtext }}</td>
            </tr>
            <tr bgcolor="#f5f5f5"  align="center" valign="center">
                <td>３じかんめ</td>
                <td>{{ timetable.ThirdPeriod }}</td>
                <td>{{ timetable.thirdtext }}</td>
            </tr>
            <tr bgcolor="#f5f5f5"  align="center" valign="center">
                <td>４じかんめ</td>
                <td>{{ timetable.FourthPeriod }}</td>
                <td>{{ timetable.fourthtext }}</td>
            </tr>
            <tr bgcolor="#f5f5f5"  align="center" valign="center">
                <td colspan="3">きゅうしょく</td>
            </tr>
            <tr bgcolor="#f5f5f5"  align="center" valign="center">
                <td colspan="3">ひるやすみ</td>
            </tr>
            <tr bgcolor="#f5f5f5"  align="center" valign="center">
                <td>５じかんめ</td>
                <td>{{ timetable.FifthPeriod }}</td>
                <td>{{ timetable.fifthtext }}</td>
            </tr>
            <tr bgcolor="#f5f5f5"  align="center" valign="center">
                <td>６じかんめ</td>
                <td>{{ timetable.SixthPeriod }}</td>
                <td>{{ timetable.sixthtext }}</td>
            </tr>
            <tr bgcolor="#f5f5f5"  align="center" valign="center">
                <td colspan="3">そうじ</td>
            </tr>
            <tr bgcolor="#f5f5f5"  align="center" valign="center">
                <td colspan="3">おわりのかい</td>
            </tr>
        </table>
        <br>
        <br>
        <table border="3" bordercolor="#00bfff" width="500" height="200" align="center">
            <tr bgcolor="#00ffff">
                <th>ひつようなもの</th>
            </tr>
            <tr bgcolor="#f5f5f5">
                <td>{{ timetable.text | linebreaksbr }}</td>
            </tr>
        </table>
        <div class="rightside-contents-form" align="center">
            <p>
                <a href="{% url 'timetable:lunchmenu_detail' timetable.id %}">きゅうしょくのこんだて</a>
            </p>
            <p>
                <a href="{% url 'timetable:timetable_list'　%}">
                    <input type="submit" value="じかんわりいちらんにもどる" class="yk-button">
                </a>
            </p>
        </div>
    </div>
{% else %}
    <div class="kokoro">
        <h1 align="center">{{ timetable.day }}の時間割</h1>
        <table border="4" bordercolor="#00bfff" width="400" height="500" align="center">
            <tr bgcolor="#00ffff" align="center" valign="center">
                <th></th>
                <th>授業</th>
                <th >内容</th>
            </tr>
            <tr bgcolor="#f5f5f5" align="center" valign="center">
                <td colspan="3">朝の会</td>
            </tr>
            <tr bgcolor="#f5f5f5" align="center" valign="center">
                <td>１時間目</td>
                <td>{{ timetable.FirstPeriod }}</td>
                <td>{{ timetable.firsttext }}</td>
            </tr>
            <tr bgcolor="#f5f5f5" align="center" valign="center">
                <td>２時間目</td>
                <td>{{ timetable.SecondPeriod }}</td>
                <td>{{ timetable.secondtext }}</td>
            </tr>
            <tr bgcolor="#f5f5f5" align="center" valign="center">
                <td>３時間目</td>
                <td>{{ timetable.ThirdPeriod }}</td>
                <td>{{ timetable.thirdtext }}</td>
            </tr>
            <tr bgcolor="#f5f5f5" align="center" valign="center">
                <td>４時間目</td>
                <td>{{ timetable.FourthPeriod }}</td>
                <td>{{ timetable.fourthtext }}</td>
            </tr>
            <tr bgcolor="#f5f5f5" align="center" valign="center">
                <td colspan="3">給食</td>
            </tr>
            <tr bgcolor="#f5f5f5" align="center" valign="center">
                <td colspan="3">昼休み</td>
            </tr>
            <tr bgcolor="#f5f5f5" align="center" valign="center">
                <td>５時間目</td>
                <td>{{ timetable.FifthPeriod }}</td>
                <td>{{ timetable.fifthtext }}</td>
            </tr>
            <tr bgcolor="#f5f5f5" align="center" valign="center">
                <td>６時間目</td>
                <td>{{ timetable.SixthPeriod }}</td>
                <td>{{ timetable.sixthtext }}</td>
            </tr>
            <tr bgcolor="#f5f5f5" align="center" valign="center">
                <td colspan="3">掃除</td>
            </tr>
            <tr bgcolor="#f5f5f5" align="center" valign="center">
                <td colspan="3">終わりの会</td>
            </tr>
        </table>
        <br>
        <br>
        <table border="3" bordercolor="#00bfff" width="500" height="200" align="center">
            <tr bgcolor="#00ffff">
                <th>必要な物</th>
            </tr>
            <tr bgcolor="#f5f5f5" >
                <td>{{ timetable.text | linebreaksbr }}</td>
            </tr>
        </table>
        <div class="rightside-contents-form" align="center">
            <p>
                <a href="{% url 'timetable:lunchmenu_detail' timetable.id %}">給食の献立</a>
            </p>
            <p>
                <a href="{% url 'timetable:timetable_list'　%}">
                    <input type="submit" value="時間割一覧に戻る" class="yk-button">
                </a>
            </p>
        </div>
    </div>
{% endif %}
{% endblock %}

templates/timetable/timetable_list.html
{% extends 'base_chat.html' %}
{% block content %}
{% if user.age < 17 %}
    <div class="nico">
       <h1 align="center">じかんわりいちらんページ</h1>
        <div class="col-8">
            <table border="3" bordercolor="#00bfff" align="center" width="300" height="200">
            <tr bgcolor="#00ffff" align="center">
                <th>ひづけ</th>
            </tr>
            {% for timetable in timetable %}
                <tr bgcolor="#f5f5f5" align="center">
                    <div class="border">
                        <td><a href="{% url 'timetable:timetable_detail' timetable.id %}">{{ timetable.day }}</a></td>
                    </div>
                </tr>
            {% endfor %}
            </table>
            <br>
        </div>
        <div class="rightside-contents-form">
             <p align="center">しぼりこみ</p>
            {% for year_month in year_month_list %}
                <div align="center">
                    <a href="{{ year_month.link }}">{{ year_month.label }}</a>
                </div>
            {% endfor %}
            <br>
            <br>
        </div>
    </div>
    </div>
{% else %}
    <div class="kokoro">
        <h1 align="center">時間割一覧ページ</h1>
        <div class="col-8">
            <table border="3" bordercolor="#00bfff" align="center" width="300" height="200">
            <tr bgcolor="#00ffff" align="center">
                <th>日付</th>
                <th>更新</th>
                <th>削除</th>
            </tr>
            {% for timetable in timetable %}
                <tr bgcolor="#f5f5f5" align="center">
                    <div class="border">
                        <td><a href="{% url 'timetable:timetable_detail' timetable.id %}">{{ timetable.day }}</a></td>
                            <td><a href="{% url 'timetable:timetable_update' timetable.id %}">更新</a></td>
                            <td><a href="{% url 'timetable:timetable_delete' timetable.id %}">削除</a></td>
                    </div>
                </tr>
            {% endfor %}
            </table>
            <br>
        </div>
        <div class="rightside-contents-form">
             <p align="center">絞り込む</p>
            {% for year_month in year_month_list %}
                <div align="center">
                    <a href="{{ year_month.link }}">{{ year_month.label }}</a>
                </div>
            {% endfor %}
            <br>
            <br>
            <p align="center">新規作成</p>
            <p align="center">
                <a href="{% url 'timetable:timetable_create' %}">
                    <input type="submit" value="時間割を作成" class="yk-button">
                </a>
            </p>
        </div>
    </div>
    </div>
{% endif %}
{% endblock %}

templates/timetable/timetable_update.html
{% extends 'base_chat.html' %}
{% block content %}
<div class="kokoro">
  <h2>時間割編集ページ</h2>
  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <div align="center">
          <input type="submit" id="save" value="更新" class="yk-button">
      </div>
  </form>
    <div align="center">
         <a href="{% url 'timetable:timetable_list' %}">
           <input type="submit" value="キャンセル" class="yk-button">
       </a>
    </div>
</div>
{% endblock %}