accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = [
    path('accounts_create/', views.AccountCreateView.as_view(), name='create'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('clear/', login_required(views.Clear.as_view()), name='clear'),
]

blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'blog'

urlpatterns = [
    path('', login_required(views.Home.as_view()), name='home'),
    path('tag/create/', login_required(views.TagCreateView.as_view()), name='tag_create'),
    path('kiji/create/', login_required(views.KijiCreateView.as_view()), name='kiji_create'),
    path('kiji/detail/<int:pk>', login_required(views.KijiDetailView.as_view()), name='kiji_detail'),
    path('kiji_update/<int:pk>/', login_required(views.KijiUpdate.as_view()), name='kiji_update'),
    path('kiji_delete/<int:pk>/',login_required(views.KijiDelete.as_view()), name='kiji_delete'),
    path('comment/create/<int:pk>',login_required(views.CommentCreateView.as_view()), name='comment_create'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('chat/', include('chat.urls')),
    path('homework/', include('homework.urls')),
    path('timetable/', include('timetable.urls')),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.utils import timezone
from django.db import models
from accounts.models import CustomUser


def get_current_name(request):
    if request.user.is_authenticated:
        return request.user.name
    else:
        return 'あ'


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=255)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('タグ名', max_length=255)

    def __str__(self):
        return self.name


class Kiji(models.Model):
    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('本文　　')
    created_at = models.DateTimeField('作成日　', default=timezone.now)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ')

    # タグは複数紐づく。また、タグを設定しないことも可能にしている(blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True, null=True, verbose_name='タグ　　')

    def __str__(self):
        return self.title


class Comment(models.Model):
    name = models.CharField('名前　　　　', default='名無し', max_length=100,)
    text = models.TextField('コメント内容')
    target = models.ForeignKey(
        Kiji, on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name='紐づく記事'
    )

    def __str__(self):
        return self.text[:15]


class Access(models.Model):
    access_no = models.PositiveIntegerField(blank=True, null=True)

blog/forms.py
from django import forms

from .models import Tag, Kiji,Comment


class TagCreateForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ('name',)


class KijiCreateForm(forms.ModelForm):
    class Meta:
        model = Kiji
        fields = ('title', 'text', 'created_at', 'category', 'tags',)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','text',)


class KijiUpdateForm(forms.ModelForm):
    class Meta:
        model = Kiji
        fields = ('title', 'text', 'created_at', 'category', 'tags',)


class SearchForm(forms.Form):
    keyword = forms.CharField(label='ニュースのキーワードをいれてね', required=False)

blog/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import redirect
from django.contrib.auth.models import User
from .forms import SearchForm, KijiCreateForm, CommentCreateForm, TagCreateForm, KijiUpdateForm
from .models import Kiji, Comment, Tag, Access


class Home(generic.ListView):
    model = Kiji
    template_name = 'blog/home.html'
    queryset = Kiji.objects.all().order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # フォーム(request.GETやrequest.POST)とすると、
        # このフォームをテンプレートで表示すると、入力済みになっている
        context['form'] = SearchForm(self.request.GET)

        Access.objects.get_or_create(id=1, defaults={'access_no': 0})
        q = Access.objects.get(id=1)
        kaisuu = q.access_no + 1
        q.access_no = kaisuu
        q.save()
        access_text = str(kaisuu)
        context['access_text'] = access_text
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = SearchForm(self.request.GET)
        form.is_valid()
        keyword = form.cleaned_data.get('keyword')
        if keyword:
            # 記事タイトルか本文のどちらかにキーワードが含まれていれば表示
            queryset = queryset.filter(Q(title__icontains=keyword) | Q(text__icontains=keyword))
        return queryset

    def users(request, user_age, user_username):
        user = get_object_or_404(User, pk=user_age)
        context2 = {
            'user': user,
        }
        # user2 = get_object_or_404(User, pk=user_username)
        # context3 = {
        #     'user2': user2,
        # }
        return context2


class KijiDetailView(generic.DetailView):
    model = Kiji
    template_name = 'blog/kiji_detail.html'

    def get_object(self, queryset=None):
        # self.kwargsは、URL内の int:pkといった部分が入っている
        kiji = Kiji.objects.get(pk=self.kwargs['pk'])
        # →Staff.objects.get(pk=1)  # 今回、URLは/staff_detail/1/
        # →Staff.objects.get(id=1)  # pkというのは、primarykeyのこと。今回ならidフィールドのこと
        return kiji

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        kiji = self.get_object()
        context['tags'] = kiji.tags.all()
        return context


class TagCreateView(generic.CreateView):
    model = Tag
    template_name = 'blog/tag_create.html'
    success_url = reverse_lazy('blog:home')
    form_class = TagCreateForm


class KijiCreateView(generic.CreateView):
    model = Kiji
    template_name = 'blog/kiji_create.html'
    success_url = reverse_lazy('blog:home')
    form_class = KijiCreateForm


class KijiUpdate(generic.UpdateView):
    model = Kiji
    form_class = KijiUpdateForm
    template_name = 'blog/kiji_update.html'
    success_url = reverse_lazy('blog:home')


class KijiDelete(generic.DeleteView):
    model = Kiji
    template_name = 'blog/kiji_delete.html'
    success_url = reverse_lazy('blog:home')


class CommentCreateView(generic.CreateView):
    model = Comment
    template_name = 'blog/comment_create.html'
    success_url = reverse_lazy('blog:home')
    form_class = CommentCreateForm

    def form_valid(self, form):
        # form.save(commit=False) データベースにはまだ保存しない
        # commit=Falseビューで、モデルのフィールドを埋めるために使う引数
        comment = form.save(commit=False)
        # Commentモデルの、targetフィールドをここで埋める
        # モデル名.objects.get(フィールド=値)  1つだけ、DBから取り出すのに使うのがget
        # url内の<int:pk>は、self.kwargs['pk'] で取得できる
        comment.target = Kiji.objects.get(pk=self.kwargs['pk'])
        comment.save()  # saveしないと保存されない
        return redirect('blog:home')

    def get_initial(self):
        initial = {}
        initial['name'] = self.request.user.username
        return initial
# Create your views here.

templates/blog/article_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>

{% endblock %}
</body>
</html>

templates/blog/article_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
<h2>記事編集</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="save" value="更新">
</form>

{% endblock %}
</body>
</html>

templates/blog/blog_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/blog/comment_create.html
{% extends 'base_chat.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <div align="center">
  <button type="submit" class="button">送信</button>
  </div>
</form>
{% endblock %}

templates/blog/home.html
{% extends 'base_chat.html' %}
{% block content %}
<div align="center">
    {% if user.age > 17 %}
    <div class ="kokoro">
        <form action ="" method=""GET>
            {{ form.as_div }}<button type="submit" class="nico">検索</button>
        </form>
<p><h2>おしらせ</h2></p>

{% for kiji in kiji_list %}
<div class="box2">
        <h3><a href="{% url 'blog:kiji_detail' kiji.pk %}">{{ kiji.title }}</a></h3>  {{ kiji.text | truncatechars:20 }} / {{ kiji.created_at }}
<!--コンテキスト使わないで表示-->
{% for tag in kiji.tags.all %}
    {{ tag.name }}
{% endfor %}
{% for comment in kiji.comment_set.all %}
<div>
    {{ comment.name }}
    {{ comment.text | truncatechars:20}}
</div>
{% endfor %}
<p>
<a href="{% url 'blog:kiji_update' kiji.pk %}">編集</a>
<a href="{% url 'blog:kiji_delete' kiji.pk %}">削除</a>
<a href="{% url 'blog:comment_create' kiji.pk %}">コメント</a>
</p>
</div>
<br>
{% endfor %}

<div class="rightside-contents-form">
    <div class="box">
    <br>
    ログインユーザー <br>{{ user.username }}<br>
    <a href="{% url 'accounts:login' %}">ログアウト</a>
    </div>
    <p>
    貴方で{{ access_text }}回目のアクセスです
    </p>
</div>
</div>

    {% else %}

    <div class ="nico">
        <form action ="" method=""GET>
            {{ form.as_div }}<button type="submit" class="nico">けんさく</button>
        </form>
<p><h2>おしらせ</h2></p>
{% for kiji in kiji_list %}
<div class="box2">
    <h1><a href="{% url 'blog:kiji_detail' kiji.pk %}">{{ kiji.title }}</a></h1>  {{ kiji.text | truncatechars:20 }} / {{ kiji.created_at }}
<!--コンテキスト使わないで表示-->
{% for tag in kiji.tags.all %}
    {{ tag.name }}
{% endfor %}
{% for comment in kiji.comment_set.all %}
<div>
    {{ comment.name }}
    {{ comment.text | truncatechars:20}}
</div>
{% endfor %}
<p>
<a href="{% url 'blog:comment_create' kiji.pk %}">コメント</a>
</p>
</div>
<br>
{% endfor %}
</p>
<div class="rightside-contents-form">
    <div class="box">
    <br>
    ログインユーザー <br>{{ user.username }}<br>
    <br><br>
    <a href="{% url 'accounts:login' %}">ログアウト</a>
    </div>
    <p>
    きみが{{ access_text }}かいめのアクセスだよ！
    </p>
</div>
</div>
    {% endif %}
</div>

{% endblock %}

templates/blog/kiji_create.html
{% extends 'base_chat.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>

{% endblock %}

templates/blog/kiji_delete.html
{% extends 'base_chat.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <p>"{{ kiji.title }}"を削除してもよろしいですか?</p>
  <input type="submit" value="削除">
</form>

{% endblock %}

templates/blog/kiji_detail.html
{% extends 'base_chat.html' %}

{% block content %}

<h1>記事詳細</h1>
<p>タイトル {{ kiji.title }}</p>
<p>本文 {{ kiji.text }}</p>
<p>作成日 {{ kiji.created_at }}</p>
<p>タグ
<!--コンテキスト使わないで表示したやつ-->
    {% for tag in kiji.tags.all %}
        {{ tag.name }}
    {% endfor %}
</p>
<p>カテゴリ {{ kiji.category.name }}</p>
<h1>コメント欄</h1>
{% for comment in kiji.comment_set.all %}
<div>
    {{ comment.name }}
    {{ comment.text }}
</div>
{% endfor %}
<a href="{% url 'blog:comment_create' kiji.pk %}">コメント作成</a>
{% endblock %}

templates/blog/kiji_update.html
{% extends 'base_chat.html' %}

{% block content %}
{% if user.age > 17 %}


<h2>記事編集</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="save" value="更新">
</form>
{% endif %}
{% endblock %}

templates/blog/tag_create.html
{% extends 'base_chat.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>

{% endblock %}