blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'blog'

urlpatterns = [
    path('', login_required(views.Home.as_view()), name='home'),
    path('tag/create/', login_required(views.TagCreateView.as_view()), name='tag_create'),
    path('kiji/create/', login_required(views.KijiCreateView.as_view()), name='kiji_create'),
    path('kiji/detail/<int:pk>', login_required(views.KijiDetailView.as_view()), name='kiji_detail'),
    path('kiji_update/<int:pk>/', login_required(views.KijiUpdate.as_view()), name='kiji_update'),
    path('kiji_delete/<int:pk>/',login_required(views.KijiDelete.as_view()), name='kiji_delete'),
    path('comment/create/<int:pk>',login_required(views.CommentCreateView.as_view()), name='comment_create'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('list/', views.ChatListView.as_view(), name='chat_list'),
    path('create/', views.ChatCreateView.as_view(), name='chat_create'),
    path('detail/<int:pk>/', views.ChatDetailView.as_view(), name='chat_detail'),
    # path('comment/create/<int:pk>/', views.CommentCreateView.as_view(), name='comment_create'),
    path('delete/<int:pk>/', views.ChatDelete.as_view(), name='chat_delete')
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('chat/', include('chat.urls')),
    path('homework/', include('homework.urls')),
    path('timetable/', include('timetable.urls')),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=255)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField('タグ名', max_length=255)

    def __str__(self):
        return self.name

class Chat(models.Model):
    title = models.CharField('たいとる', max_length=255)
    upname = models.CharField('おなまえ', default='名無し', max_length=255)
    text = models.TextField('ほんぶん')
    created_at = models.DateTimeField('ひにち　', default=timezone.now)
    category = models.ForeignKey(Category, blank=True, null=True,on_delete=models.PROTECT, verbose_name='カテゴリ')
    image = models.ImageField('しゃしん', null=True, blank=True, upload_to='chat_images/')
    # タグは複数紐づく。また、タグを設定しないことも可能にしている(blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True, null=True, verbose_name='タグ　　')

    def __str__(self):
        return self.title

class Comment(models.Model):
    name = models.CharField('名前', default='名無し',max_length=255)
    text = models.TextField('コメント内容')
    target = models.ForeignKey(
        Chat, on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name='紐づく記事'
    )

chat/forms.py
from django import forms
from .models import Chat, Comment


class ChatCreateForm(forms.ModelForm):

    class Meta:
        model = Chat
        # ページに表示したいモデルのフィールドを、文字列で書きます
        fields = ('title','upname','text','created_at','category','image','tags',)

class ChatUpdateForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ('title','text','created_at','category','tags',)

# class SearchForm(forms.Form):
#     keyword = forms.CharField(label='キーワード', required=False)

class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','text',) # targetフィールドを含めない

class SearchForm(forms.Form):
    keyword = forms.CharField(label='キーワード', required=False)

chat/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import Chat, Comment
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse_lazy
from .forms import ChatCreateForm, CommentCreateForm, SearchForm
from django.contrib.auth.models import User
from django.db.models import Q
# Create your views here.
class ChatListView(generic.ListView):
    model = Chat
    template_name = 'chat/chat_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SearchForm(self.request.GET)
        return context

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-created_at')
        form = SearchForm(self.request.GET)
        form.is_valid()
        keyword = form.cleaned_data.get('keyword')
        if keyword:
            queryset = queryset.filter(
                # 記事のタイトルか、本文のどちらかにキーワードが含まれているものを絞り込む
                Q(title__icontains=keyword) | Q(text__icontains=keyword)
            )
        return queryset


class ChatDetailView(generic.CreateView):
    model = Chat
    template_name = 'chat/chat_detail.html'
    form_class = CommentCreateForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        chat = Chat.objects.get(pk=self.kwargs['pk'])
        comment.target = chat
        form.save()
        return redirect('chat:chat_detail', pk=chat.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['chat'] = Chat.objects.get(pk=self.kwargs['pk'])
        return context

    def get_initial(self):
        initial = {}
        initial['name'] = self.request.user.username
        return initial


class ChatCreateView(generic.CreateView):
    model = Chat
    template_name = 'chat/chat_create.html'
    success_url = reverse_lazy('chat:chat_list')
    form_class = ChatCreateForm

    def get_initial(self):
        initial = {}
        initial['upname'] = self.request.user.username
        return initial

class ChatDelete(generic.DeleteView):
    # フォームは必要なし
    model = Chat
    template_name = 'chat/chat_delete.html'
    success_url = reverse_lazy('chat:chat_list')

templates/chat/a.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body{
        background-color:red;
        }
    </style>
</head>
<body>

</body>
</html>

templates/chat/chat_confirm.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

templates/chat/chat_create.html
{% extends 'base_chat.html' %}

{% block content %}

{% if user.age > 17 %}
<h1>トークテーマ投稿</h1>
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_div }}
  <button class="button" type="submit">投稿</button>
</form>
<hr>
{% else %}
<h1>おはなしをつくる</h1>
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_div }}
  <button class="button" type="submit">とうこうする</button>
</form>
<hr>
{% endif %}

<div class="rightside-contents">

</div>

{% endblock %}

templates/chat/chat_delete.html
{% extends 'base_chat.html' %}

{% block content %}

{% if user.age > 17 %}
<form method="post">
  {% csrf_token %}
  <p>"{{ chat.title }}"を削除してもよろしいですか?</p>
  <input type="submit" class="button" value="削除">
</form>
<button type="button" class="button" onclick="history.back()">戻る</button>
{% else %}

<form method="post">
  {% csrf_token %}
  <p>"{{ chat.title }}"をけしてもだいじょうぶ?</p>
  <input type="submit" class="button" value="うん！！！">
</form>
<button type="button" class="button" onclick="history.back()">やっぱダメ！！！</button>
{% endif %}

{% endblock %}

templates/chat/chat_detail.html
{% extends 'base_chat.html' %}
{% block content %}
    <h1>{{ chat.title }}</h1>
    <p>投稿者：{{ chat.upname }}</p>
    {% if chat.image %}
    <img class="chat-image" src="{{ chat.image.url }}/">
    {% endif %}
    <p>{{ chat.text }}</p>
    <p>投稿日：{{ chat.created_at|date:'Y/m/d/G:i'}}</p>
    <p>カテゴリー：{{ chat.category }}</p>
    <p>
        タグ：
        {% for tag in chat.tags.all %}
            {{ tag.name }}
        {% endfor %}
    </p>
    <p>
        <a href="{% url 'chat:chat_delete' chat.pk %}">この投稿を削除する</a>
    </p>
    <hr>

{% for comment in chat.comment_set.all %}
    <div class="ohanasiBox">
        <h2>{{ comment.name }}</h2>
        <p>{{ comment.text | linebreaks }}</p>
    </div>
    <hr>
{% endfor %}

<!-- コメント機能 -->
{% if user.age > 17 %}
<div class="rightside-contents-form">
    <form action="" method="POST">
      {% csrf_token %}
      {{ form.as_div }}
      <button class="button" type="submit">送信</button>
    </form>
</div>
{% else %}
<div class="rightside-contents-form">
    <form action="" method="POST">
      {% csrf_token %}
      {{ form.as_div }}
      <button class="button" type="submit">おくる</button>
    </form>
</div>
{% endif %}
<!-- ここまで -->

<!--<a href="{% url 'chat:chat_list' %}">いちらんにもる</a>-->
{% endblock %}

templates/chat/chat_list.html
{% extends 'base_chat.html' %}
{% block content %}

<h1>おはなしいちらん</h1>
<form action="" method="GET">
  {{ form.as_div }}
  <button type="submit">おはなしをさがす</button>
</form>
    {% for chat in chat_list %}
    <div class="ohanasiBox">
      <h2>
          <a href="{% url 'chat:chat_detail' chat.pk %}">{{ chat.title }}</a>
      </h2>
        <p>{{ chat.created_at|date:'Y/m/d/G:i'}}</p>
      {{ chat.text | truncatechars:30}}
    </div>
    {% endfor %}

<a class="button" href="{% url 'chat:chat_create' %}">おはなしをつくる</a>

{% endblock %}

templates/chat/comment_confirm.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

templates/chat/comment_create.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>
{% endblock %}