blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'blog'

urlpatterns = [
    path('', login_required(views.Home.as_view()), name='home'),
    path('tag/create/', login_required(views.TagCreateView.as_view()), name='tag_create'),
    path('kiji/create/', login_required(views.KijiCreateView.as_view()), name='kiji_create'),
    path('kiji/detail/<int:pk>', login_required(views.KijiDetailView.as_view()), name='kiji_detail'),
    path('kiji_update/<int:pk>/', login_required(views.KijiUpdate.as_view()), name='kiji_update'),
    path('kiji_delete/<int:pk>/',login_required(views.KijiDelete.as_view()), name='kiji_delete'),
    path('comment/create/<int:pk>',login_required(views.CommentCreateView.as_view()), name='comment_create'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('list/', views.ChatListView.as_view(), name='chat_list'),
    path('create/', views.ChatCreateView.as_view(), name='chat_create'),
    path('detail/<int:pk>/', views.ChatDetailView.as_view(), name='chat_detail'),
    # path('comment/create/<int:pk>/', views.CommentCreateView.as_view(), name='comment_create'),
    path('delete/<int:pk>/', views.ChatDelete.as_view(), name='chat_delete')
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('chat/', include('chat.urls')),
    path('homework/', include('homework.urls')),
    path('timetable/', include('timetable.urls')),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homework/urls.py
from django.urls import path
from . import views

app_name = 'homework'

urlpatterns = [
    path('homework', views.IndexView.as_view(), name='homework'),
    path('homework_list/', views.PostListView.as_view(), name='homework_list'),
    path('homework_create/', views.PostCreateView.as_view(), name='homework_create'),
    path('homework_student/', views.StudentCreateView.as_view(), name='homework_student'),
    path('homework_teacher/', views.TeacherListView.as_view(), name='homework_teacher'),
    path('homework_delete/<int:pk>/', views.HomeworkDeleteView.as_view(), name='homework_delete'),
]

timetable/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'timetable'

urlpatterns =[
    # path('test/', views.Test.as_view(), name='test'),
    path('timetable_create/', views.TimetableCreateView.as_view(), name='timetable_create'),
    # path('timetable_list/', views.TimetableListView.as_view(), name='timetable_list'),
    path('timetable_list/', views.TimetableView.as_view(), name='timetable_list'),
    path('timetable_detail/<int:pk>/', views.TimetableDetailView.as_view(), name='timetable_detail'),
    path('timetable_delete/<int:pk>/', views.TimetableDeleteView.as_view(), name='timetable_delete'),
    path('timetable_update/<int:pk>/', views.TimetableUpdateView.as_view(), name='timetable_update'),
    path('subject_create/', views.SubjectCreateView.as_view(), name='subject_create'),
    path('subject_list/', views.SubjectListView.as_view(), name='subject_list'),
    # path('lunchmenu_create/', views.LunchmenuCreateView.as_view(), name='lunchmenu_create'),
    # path('lunchmenu_create/<int:pk>', views.LunchmenuCreateView.as_view(), name='lunchmenu_create'),
    # path('lunchmenu_list/', views.LunchmenuListView.as_view(), name='lunchmenu_list'),
    path('lunchmenu_detail/<int:pk>/', views.LunchmenuDetailview.as_view(), name='lunchmenu_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
  {% load static %}
  <html lang="ja">
  <head>
      <link rel="stylesheet" href="{% static 'css/kawakami.css' %}">
      <link rel="icon" type="image/png" href="{% static 'icon/favicon.ico' %}">
      <title>{% block title %}SNS{% endblock %}</title>
      <style>
          body {
            background-color: #48d1cc;
          }
      </style>
  </head>
  <body>
      <div id="content">
        {% block content %}{% endblock %}
      </div>
  </body>
  </html>

templates/base_chat.html
<!DOCTYPE html>
  {% load static %}
  <html lang="ja">
  <head>
      <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet">
      <link href="https://fonts.googleapis.com/earlyaccess/kokoro.css" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/style_chat.css' %}?a=2">
      <link rel="stylesheet" href="{% static 'css/kawakami.css' %}">
      <link rel="stylesheet" href="{% static 'css/yasu.css' %}">
      <link rel="stylesheet" href="{% static 'css/erena.css' %}">
      <link rel="icon" type="image/png" href="{% static 'icon/favicon2.ico' %}">
      <title>{% block title %}ランセル.net{% endblock %}</title>
  </head>
  <body>
  {% if user.age > 17 %}
    <div class ="kokoro">
        <header>
            <a href="{% url 'blog:home' %}"> <img src="/static/weblogo2.png" class="logo" ></a>
        <nav class="nav">
            <div class="menu-item">記事作成<a class="Link" href="{% url 'blog:kiji_create' %}"></a></div>
            <div class="menu-item">スレッド一覧<a class="Link" href="{% url 'chat:chat_list' %}"></a></div>
            <div class="menu-item">スレッドを立てる<a class="Link" href="{% url 'chat:chat_create' %}"></a></div>
            <div class="menu-item">宿題一覧<a class="Link" href="{% url 'homework:homework_list' %}"></a></div>
            <div class="menu-item">提出一覧<a class="Link" href="{% url 'homework:homework_teacher' %}"></a></div>
            <div class="menu-item">宿題作成<a class="Link" href="{% url 'homework:homework_create' %}"></a></div>
            <div class="menu-item">時間割一覧<a class="Link" href="{% url 'timetable:timetable_list' %}"></a></div>
            <div class="menu-item">時間割作成<a class="Link" href="{% url 'timetable:timetable_create' %}"></a></div>
        </nav>
      </header>
    </div>
　{% else %}
    <div class="nico">
        <header>
            <a href="{% url 'blog:home' %}"><img src="/static/weblogo2.png" class="logo"></a>
        <nav class="nav">
            <div class="menu-item">おはなしいちらん<a class="Link" href="{% url 'chat:chat_list' %}"></a></div>
            <div class="menu-item">おはなしつくる<a class="Link" href="{% url 'chat:chat_create' %}"></a></div>
            <div class="menu-item">しゅくだい<a class="Link" href="{% url 'homework:homework_list' %}"></a></div>
            <div class="menu-item">しゅくだいていしゅつ<a class="Link" href="{% url 'homework:homework_student' %}"></a></div>
            <div class="menu-item">じかんわり<a class="Link" href="{% url 'timetable:timetable_list' %}"></a></div>
        </nav>
      </header>
    </div>
  {% endif %}

      <div class="main">
          {% block content %}{% endblock %}
      </div>
<div class="rightside-contents">

</div>
  </body>

  </html>

templates/base_timetable.html
<!DOCTYPE html>
  {% load static %}
  <html lang="ja">
  <head>
      <link rel="stylesheet" href="{% static 'css/style_chat.css' %}">
      <link rel="stylesheet" href="{% static 'css/kawakami.css' %}">
      <link rel="stylesheet" href="{% static 'css/yasu.css' %}">
      <link rel="stylesheet" href="{% static 'css/erena.css' %}">
      <link rel="icon" type="image/png" href="{% static 'icon/favicon.ico' %}">
      <title>{% block title %}(仮称)小学生専用Webサイト{% endblock %}</title>
  </head>
  <body>
      <header>
        <h1 class="title">タイトル</h1>
        <nav class="nav">
            <h2 class="menu-item"><a href="{% url 'blog:home' %}">トップページ</a></h2>
            <h2 class="menu-item"><a href="{% url 'chat:chat_list' %}">チャット</a></h2>
            <h3 class="menu-item"><a href="{% url 'chat:chat_create' %}">はなしをつくる</a></h3>
            <h2 class="menu-item"><a href="{% url 'homework:homework_list' %}">しゅくだい</a></h2>
            <h2 class="menu-item"><a href="{% url 'timetable:timetable_list' %}">じかんわり</a></h2>
            <h3 class="menu-item"><a href="{% url 'timetable:timetable_create' %}">じかんわり作成</a></h3>
        </nav>
      </header>

      <div class="main">
          {% block content %}{% endblock %}
      </div>
  </body>
  </html>